"""Guard-fires proofs for both live-repo mutation guard entry points (F2, SA-0MUG30HV8004HV94).

Covers:

- AC3 — the repo-root-conftest guard (``skill/shared/live_repo_guard.py``)
  fires on a mutation and names the offending test, run as a real nested
  pytest session inside a ``tmp_path`` repository;
- AC4 — the ``run_tests.py`` snapshot guard (F4) exits non-zero when the
  configured suite command mutates a ref;
- AC5 — no false positives: churn in an unrelated repository, a no-op run, and
  agent-worktree churn (branch advance, plus registration/removal mid-run
  including the ``--track`` branch config) do not trip the guard
  (SA-0MUINEW6X0034C65).

No live checkout is mutated to obtain any proof; every mutation happens in a
``tmp_path`` repository created through ``shared.git_sandbox``.
"""
from __future__ import annotations

import contextlib
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

from shared import git_sandbox as gs
from test.scripts.run_tests import guarded_run_all

REPO_ROOT = Path(__file__).resolve().parents[1]
GUARD_MODULE = REPO_ROOT / "skill" / "shared" / "live_repo_guard.py"
RUN_TESTS = REPO_ROOT / "skill" / "test" / "scripts" / "run_tests.py"
MARKER_ENV = "LIVE_REPO_GUARD_ACTIVE"


def _child_env() -> dict[str, str]:
    """Environment for a nested run: no repo overrides, no guard marker."""
    env = gs.sanitized_git_env()
    env.pop(MARKER_ENV, None)
    return env


def _init_guard_repo(base: Path, name: str = "victim") -> Path:
    """Create a committed repo with the conventional Python ignores.

    The initial commit gives the default branch a valid object so fixtures can
    create branches; the ``.gitignore`` mirrors a real repo (``__pycache__`` and
    ``.pytest_cache`` are generated by the nested pytest run and must not be
    mistaken for a mutation).
    """
    repo = gs.init_repo(base / name)
    (repo / ".gitignore").write_text(
        "__pycache__/\n*.pyc\n.pytest_cache/\n.worklog/\n", encoding="utf-8"
    )
    (repo / "README.md").write_text("fixture\n", encoding="utf-8")
    gs.commit_all(repo, "init")
    return repo


def _write_guard_conftest(repo: Path) -> None:
    """Write a conftest that arms the shared guard for *repo*."""
    (repo / "conftest.py").write_text(
        textwrap.dedent(
            f"""
            import importlib.util
            from pathlib import Path

            _GUARD = Path({str(GUARD_MODULE)!r})
            _spec = importlib.util.spec_from_file_location("_live_repo_guard", _GUARD)
            _module = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_module)


            def pytest_configure(config):
                _module.register(config, root=Path(__file__).resolve().parent)
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )


def _run_nested_pytest(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", *args],
        cwd=str(repo),
        env=_child_env(),
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )


# ---------------------------------------------------------------------------
# AC3 — conftest entry point
# ---------------------------------------------------------------------------


class TestConftestGuardFires:
    def test_mutating_test_is_failed_and_named(self, tmp_path):
        repo = _init_guard_repo(tmp_path)
        _write_guard_conftest(repo)
        (repo / "test_mutator.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            "def test_creates_a_branch():\n"
            "    subprocess.run(\n"
            "        ['git', '-C', str(Path(__file__).resolve().parent),\n"
            "         'branch', 'intruder'],\n"
            "        check=True,\n"
            "    )\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(repo)

        combined = proc.stdout + proc.stderr
        assert proc.returncode != 0, combined
        assert "live-repo mutation" in combined
        assert "test_creates_a_branch" in combined
        # The guard is real: the branch really was created.
        assert gs.run_git(repo, ["rev-parse", "--verify", "refs/heads/intruder"]).returncode == 0

    def test_config_rewrite_is_failed_and_named(self, tmp_path):
        """Config rewrites are still genuine mutations after the exclusion fix."""
        repo = _init_guard_repo(tmp_path)
        _write_guard_conftest(repo)
        (repo / "test_config_mutator.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            "def test_rewrites_config():\n"
            "    subprocess.run(['git', '-C', str(Path(__file__).resolve().parent),\n"
            "                    'config', '--local', 'user.name', 'intruder'], check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(repo)

        combined = proc.stdout + proc.stderr
        assert proc.returncode != 0, combined
        assert "live-repo mutation" in combined
        assert "user.name" in combined


# ---------------------------------------------------------------------------
# AC4 — run_tests.py entry point
# ---------------------------------------------------------------------------


class TestRunTestsGuardFires:
    def test_configured_command_mutating_a_ref_fails_the_run(self, tmp_path):
        repo = _init_guard_repo(tmp_path)
        (repo / ".pi").mkdir()
        (repo / ".pi" / "test-config.json").write_text(
            json.dumps({"suiteCommands": ["bash mutate.sh"]}), encoding="utf-8"
        )
        (repo / "mutate.sh").write_text(
            "#!/bin/sh\ngit branch intruder\n", encoding="utf-8"
        )
        (repo / "mutate.sh").chmod(0o755)
        (repo / "tests").mkdir()
        (repo / "tests" / "test_noop.py").write_text(
            "def test_ok():\n    assert True\n", encoding="utf-8"
        )

        proc = subprocess.run(
            [
                sys.executable,
                str(RUN_TESTS),
                "--project-root",
                str(repo),
                "--scope",
                "full",
                "--json",
            ],
            cwd=str(repo),
            env=_child_env(),
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )

        combined = proc.stdout + proc.stderr
        assert proc.returncode != 0, combined
        assert "live-repo mutation" in combined
        assert "refs/heads/intruder" in combined

    def test_clean_configured_suite_passes(self, tmp_path):
        repo = _init_guard_repo(tmp_path, "clean")
        (repo / ".pi").mkdir()
        (repo / ".pi" / "test-config.json").write_text(
            json.dumps({"suiteCommands": ["bash noop.sh"]}), encoding="utf-8"
        )
        (repo / "noop.sh").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        (repo / "noop.sh").chmod(0o755)

        proc = subprocess.run(
            [
                sys.executable,
                str(RUN_TESTS),
                "--project-root",
                str(repo),
                "--scope",
                "full",
                "--json",
            ],
            cwd=str(repo),
            env=_child_env(),
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )

        assert proc.returncode == 0, proc.stdout + proc.stderr


class TestGuardedRunAllOwnership:
    """Guard-ownership parity at the canonical programmatic API (SA-0MUH1MJL6003767Q).

    ``guarded_run_all`` is the single source of truth for outer live-repo
    guard ownership: the CLI and ``implement.py``'s finish gate both delegate
    to it. These tests exercise it programmatically and assert the ownership
    contract — owns when the marker is unset (snapshot + detect + clear),
    stands down when the marker is already set by an outer guard.
    """

    def _isolate_pacer(self, monkeypatch) -> None:
        """Neutralise the host-wide test semaphore for in-process runs.

        The guard-ownership contract is orthogonal to concurrency pacing; a
        saturated shared semaphore (other agents running suites) would make
        these tests wait/time out. The pacer is exercised elsewhere
        (SA-0MTG5U75A001F1RG).
        """
        from test.scripts import run_tests as _rt

        monkeypatch.setattr(_rt, "_test_concurrency_slot", lambda: contextlib.nullcontext())

    def _mutating_repo(self, tmp_path: Path, name: str = "victim") -> Path:
        repo = _init_guard_repo(tmp_path, name)
        (repo / ".pi").mkdir()
        (repo / ".pi" / "test-config.json").write_text(
            json.dumps({"suiteCommands": ["bash mutate.sh"]}), encoding="utf-8"
        )
        (repo / "mutate.sh").write_text(
            "#!/bin/sh\ngit branch intruder\n", encoding="utf-8"
        )
        (repo / "mutate.sh").chmod(0o755)
        return repo

    def test_owns_checkout_and_detects_mutation(self, tmp_path, monkeypatch):
        """Marker unset → own the checkout: mutation detected, marker cleared."""
        repo = self._mutating_repo(tmp_path)
        monkeypatch.delenv(MARKER_ENV, raising=False)
        self._isolate_pacer(monkeypatch)

        result = guarded_run_all(cwd=repo, use_cache=False)

        assert result["success"] is False
        assert "live_repo_mutation" in result
        assert "intruder" in result["live_repo_mutation"]
        assert MARKER_ENV not in os.environ

    def test_clean_run_reports_no_mutation(self, tmp_path, monkeypatch):
        """Marker unset, clean suite → success with no mutation key."""
        repo = _init_guard_repo(tmp_path, "clean")
        (repo / ".pi").mkdir()
        (repo / ".pi" / "test-config.json").write_text(
            json.dumps({"suiteCommands": ["bash noop.sh"]}), encoding="utf-8"
        )
        (repo / "noop.sh").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        (repo / "noop.sh").chmod(0o755)
        monkeypatch.delenv(MARKER_ENV, raising=False)
        self._isolate_pacer(monkeypatch)

        result = guarded_run_all(cwd=repo, use_cache=False)

        assert result["success"] is True
        assert "live_repo_mutation" not in result
        assert MARKER_ENV not in os.environ

    def test_stands_down_when_marker_preset(self, tmp_path, monkeypatch):
        """Marker preset → an outer guard owns; do not detect or clear."""
        repo = self._mutating_repo(tmp_path, "nested")
        monkeypatch.setenv(MARKER_ENV, "1")
        self._isolate_pacer(monkeypatch)

        result = guarded_run_all(cwd=repo, use_cache=False)

        # The nested call must NOT double-report the mutation...
        assert "live_repo_mutation" not in result
        # ...and must not clear the outer guard's marker.
        assert os.environ.get(MARKER_ENV) == "1"

    def test_marker_set_during_owned_run(self, tmp_path, monkeypatch):
        """Marker unset → set for the duration of run_all (inner guard down)."""
        repo = _init_guard_repo(tmp_path, "owned")
        (repo / ".pi").mkdir()
        (repo / ".pi" / "test-config.json").write_text(
            json.dumps({"suiteCommands": ["bash probe.sh"]}), encoding="utf-8"
        )
        # Probe writes the marker value it observes to a file OUTSIDE the repo
        # (writing inside the checkout would itself be a mutation), proving the
        # marker is exported to the suite subprocess (so the inner conftest
        # guard stands down) while the outer guard owns the checkout.
        probe_out = tmp_path / "marker_seen.txt"
        (repo / "probe.sh").write_text(
            f'#!/bin/sh\nprintf "%s" "$LIVE_REPO_GUARD_ACTIVE" > "{probe_out}"\n',
            encoding="utf-8",
        )
        (repo / "probe.sh").chmod(0o755)
        monkeypatch.delenv(MARKER_ENV, raising=False)
        self._isolate_pacer(monkeypatch)

        result = guarded_run_all(cwd=repo, use_cache=False)

        assert result["success"] is True
        assert probe_out.read_text(encoding="utf-8") == "1"
        assert MARKER_ENV not in os.environ


# ---------------------------------------------------------------------------
# AC5 — no false positives
# ---------------------------------------------------------------------------


class TestNoFalsePositives:
    def test_unrelated_repo_churn_does_not_trip_the_guard(self, tmp_path):
        root = _init_guard_repo(tmp_path, "root")
        _write_guard_conftest(root)
        other = _init_guard_repo(tmp_path, "other")
        (root / "test_ok.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"OTHER = Path({str(other)!r})\n\n"
            "def test_churns_other_repo():\n"
            "    subprocess.run(['git', '-C', str(OTHER), 'branch', 'other-only'],\n"
            "                   check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(root)

        assert proc.returncode == 0, proc.stdout + proc.stderr
        assert gs.run_git(other, ["rev-parse", "--verify", "refs/heads/other-only"]).returncode == 0

    def test_noop_session_reports_clean(self, tmp_path):
        root = _init_guard_repo(tmp_path, "root")
        _write_guard_conftest(root)
        (root / "test_ok.py").write_text(
            "def test_ok():\n    assert True\n", encoding="utf-8"
        )

        proc = _run_nested_pytest(root)

        assert proc.returncode == 0, proc.stdout + proc.stderr

    def test_agent_worktree_churn_does_not_trip_the_guard(self, tmp_path):
        root = _init_guard_repo(tmp_path, "root")
        agent_wt = root / ".worklog" / "worktrees" / "wl-agent"
        gs.add_worktree(root, agent_wt, "wl-agent")
        _write_guard_conftest(root)
        (root / "test_ok.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"WT = Path({str(agent_wt)!r})\n\n"
            "def test_agent_worktree_commits():\n"
            "    (WT / 'agent.txt').write_text('agent')\n"
            "    subprocess.run(['git', '-C', str(WT), 'add', '-A'], check=True)\n"
            "    subprocess.run(['git', '-C', str(WT), 'commit', '-qm', 'agent work'],\n"
            "                   check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(root)

        assert proc.returncode == 0, proc.stdout + proc.stderr

    def test_worktree_registration_churn_does_not_trip_the_guard(self, tmp_path):
        """Registering an agent worktree mid-run is churn, not a mutation.

        Regression for SA-0MUINEW6X0034C65: the excluded set grows while the
        authoritative diff stays empty, which used to fail the running test
        with ``(no differences)``.
        """
        root = _init_guard_repo(tmp_path, "root")
        agent_wt = root / ".worklog" / "worktrees" / "wl-mid"
        _write_guard_conftest(root)
        (root / "test_registers_worktree.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"ROOT = Path({str(root)!r})\n"
            f"WT = Path({str(agent_wt)!r})\n\n"
            "def test_registers_worktree():\n"
            "    subprocess.run(['git', '-C', str(ROOT), 'worktree', 'add',\n"
            "                    '-b', 'wl-mid', str(WT)], check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(root)

        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, combined
        assert "live-repo mutation" not in combined
        assert agent_wt.exists()  # the worktree really was registered

    def test_tracked_worktree_registration_churn_does_not_trip_the_guard(
        self, tmp_path
    ):
        """``--track`` registration writes branch config: still not a mutation."""
        root = _init_guard_repo(tmp_path, "root")
        agent_wt = root / ".worklog" / "worktrees" / "wl-mid"
        _write_guard_conftest(root)
        (root / "test_registers_tracked_worktree.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"ROOT = Path({str(root)!r})\n"
            f"WT = Path({str(agent_wt)!r})\n\n"
            "def test_registers_tracked_worktree():\n"
            "    subprocess.run(['git', '-C', str(ROOT), 'worktree', 'add',\n"
            "                    '--track', '-b', 'wl-mid', str(WT), 'dev'],\n"
            "                   check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(root)

        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, combined
        assert "live-repo mutation" not in combined

    def test_worktree_removal_churn_does_not_trip_the_guard(self, tmp_path):
        """Removing an agent worktree mid-run (branch retained) is not a mutation."""
        root = _init_guard_repo(tmp_path, "root")
        agent_wt = root / ".worklog" / "worktrees" / "wl-agent"
        gs.add_worktree(root, agent_wt, "wl-agent")
        _write_guard_conftest(root)
        (root / "test_removes_worktree.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"ROOT = Path({str(root)!r})\n"
            f"WT = Path({str(agent_wt)!r})\n\n"
            "def test_removes_worktree():\n"
            "    subprocess.run(['git', '-C', str(ROOT), 'worktree', 'remove', str(WT)],\n"
            "                   check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(root)

        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, combined
        assert "live-repo mutation" not in combined

    def test_linked_worktree_guard_ignores_sibling_worktree_churn(self, tmp_path):
        """Guard armed at a linked-worktree root ignores sibling churn.

        ``implement.py finish`` runs the suite from a linked worktree; the
        exclusion anchor must therefore be the main checkout, or every sibling
        commit looks like a mutation (SA-0MUINEW6X0034C65).
        """
        root = _init_guard_repo(tmp_path, "root")
        guarded_wt = root / ".worklog" / "worktrees" / "wl-guarded"
        sibling_wt = root / ".worklog" / "worktrees" / "wl-sibling"
        gs.add_worktree(root, guarded_wt, "wl-guarded")
        gs.add_worktree(root, sibling_wt, "wl-sibling")
        _write_guard_conftest(guarded_wt)
        (guarded_wt / "test_ok.py").write_text(
            "import subprocess\n"
            "from pathlib import Path\n\n"
            f"SIBLING = Path({str(sibling_wt)!r})\n\n"
            "def test_sibling_commits():"
            "\n"
            "    (SIBLING / 'sibling.txt').write_text('sibling')\n"
            "    subprocess.run(['git', '-C', str(SIBLING), 'add', '-A'], check=True)\n"
            "    subprocess.run(['git', '-C', str(SIBLING), 'commit', '-qm', 'sibling work'],\n"
            "                   check=True)\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(guarded_wt)

        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, combined
        assert "live-repo mutation" not in combined


# ---------------------------------------------------------------------------
# Teardown ordering — guard must run AFTER fixture finalisation
# ---------------------------------------------------------------------------


class TestTeardownRunsAfterFixtureFinalisation:
    """Regression: the guard's own ``subprocess`` call must not observe a
    still-active ``monkeypatch`` of ``subprocess``.

    ``pytest_runtest_teardown`` is the hook pytest uses to finalise fixtures,
    including ``monkeypatch``. If the guard's implementation of that hook runs
    first, a test that replaces ``subprocess.Popen`` (as the audit queue tests
    do) leaves the replacement active while the guard snapshots the repo — the
    guard then calls ``subprocess.run`` and raises
    ``TypeError: ... does not support the context manager protocol``, the
    monkeypatch finaliser never runs, and every later test errors.
    """

    def test_monkeypatched_subprocess_popen_does_not_break_guard(self, tmp_path):
        repo = _init_guard_repo(tmp_path)
        _write_guard_conftest(repo)
        (repo / "test_patches_subprocess.py").write_text(
            "import subprocess\n\n"
            "class _NoContextPopen:\n"
            "    returncode = 0\n"
            "    def communicate(self, timeout=None):\n"
            "        return '', ''\n"
            "    def kill(self):\n"
            "        pass\n\n"
            "def test_patches_popen(monkeypatch):\n"
            "    monkeypatch.setattr(subprocess, 'Popen', _NoContextPopen)\n"
            "    assert subprocess.Popen is _NoContextPopen\n",
            encoding="utf-8",
        )

        proc = _run_nested_pytest(repo)

        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, combined
        assert "TypeError" not in combined, combined
        assert "live-repo mutation" not in combined, combined
